spring.application.name=tuskersApp
#spring.data.mongodb.uri=mongodb+srv://tkausaf:2014Germany@ausafcluster0.uf9wvlt.mongodb.net/?appName=AusafCluster0
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=tuskersDb

